site_name: Introdução ao Archicad
use_directory_urls: false

copyright: Copyright &copy; 2025 Fernando Ferraz Ribeiro

theme:
  features:
    # copy button on code blocks
    - content.code.copy
    #- navigation.sections
    - toc.integrate
    #- navigation.tabs
  name: material   
  language: en-custom
  custom_dir: docs\overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: blue

site_url: "https://255ribeiro.github.io/intro_archicad/"
repo_url: "https://github.com/255ribeiro/intro_archicad/"
repo_name: "255ribeiro/intro_archicad" 

nav:
  - Home: index.md
  - Referências para modelagem: exemplo_projeto/projeto_modelo.md
  - Interface: interface_arch/interface.md
  - Modelagem:
    - Inserindo desenhos de referência: folhas_de_trabalho/referencias.md
    - Níveis de pisos: pisos/pisos.md
    - Paredes:
      - inserção: paredes/paredes.md
      - Junções: paredes/juncoes.md
    - Esquadrias:
      - Portas e janelas: janelas_portas/janelas_portas.md
    - Paredes cortina: paredes_cortina/paredes_cortina.md
    - Composições: composicoes/composicoes.md
    - Cobertura: cobertura/cobertura.md
    - Escadas: escadas/escadas.md
  - Informações de desenho:
    - cotas: dimensoes/dimensoes.md
    - Zonas: zonas/zonas.md
  - Impressão:
    - Canetas: impressao/canetas/canetas.md
    - mapa de vistas: impressao/mapa_de_vistas.md
    - Livro de Leiautes: impressao/livro_de_layouts.md
    - Conjunto Publicador: impressao/conjunto_pup.md
    - Representação gráfica: impressao/representacao.md
  - Terreno:
    - Modelagem de Terrenos: ./terreno/terreno_modelagem.md
    - Geração de terreno utilizado o Blender: ./terreno/terreno_extra/terreno_blender.md
  
  - Roteiros:
    - Roteiro aula 01: roteiros/roteiro_aula_01.md
    - Roteiro aula 02: roteiros/roteiro_aula_02.md
    - Roteiro aula 03: roteiros/roteiro_aula_03.md
    - Roteiro aula 04: roteiros/roteiro_aula_04.md
    - Roteiro aula 05: roteiros/roteiro_aula_05.md
    - Roteiro aula 06: roteiros/roteiro_aula_06.md
    - Roteiro aula 07: roteiros/roteiro_aula_07.md
    - Roteiro aula 08: roteiros/roteiro_aula_08.md
    - Roteiro aula 09: roteiros/roteiro_aula_09.md
    - Roteiro aula 10: roteiros/roteiro_aula_10.md
  

markdown_extensions:
  - pymdownx.highlight:
     anchor_linenums: true
     line_spans: __span
     pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      toc_depth: 1

extra_css:
  - overrides/css/extra_css.css

plugins:
  - mkdocs-jupyter:
      #execute: True
      include_source: True